### ISSUE TITLE
oplogtoredis support

### ISSUE THREAD

**Issue by vlasky** [ramezrafla/redis-oplog#17] opened 2021-07-18 11:29 UTC
Hi Ramez - another question:

I note this fork of your fork that claims to have implemented a "fix to work with oplogtoredis".

https://github.com/crisis24/redis-oplog/commit/fc77c9bf7125d8cc6b11980be643eab7cdd1b836

This sounds positive. Do you have any opinions about the modifications in this commit?

**Comment by ramezrafla** [comment] 2021-07-18 11:34
Hi Vlad

We said we are looking into ways to support oplogtoredis - the problem is that it only sends a message of changes to the db (I believe it only provides the doc _id). This meant we have to refetch the doc from Mongo. So as of yet, I don’t see how we can do it without changing oplogtoredis (to transmit the full changes not just the _id)

**Comment by ramezrafla** [comment] 2021-07-18 22:57
@vlasky 
I am taking a closer look at this fork -- I'll message the developer to get insight if need be.

**Comment by ramezrafla** [comment] 2022-09-20 02:24
oplogtoredis support break serious design assumptions. An extra DB query is required to support it. Closing ...

**Closed as completed by ramezrafla** 2022-09-20 02:24 UTC
